name: "Dependency Analysis"

on: [push, pull_request]

jobs:

  validation:
    # Skip if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip dependency analysis')"
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Gradle Wrapper validation
        uses: gradle/wrapper-validation-action@v1

  dependencyAnalysis:
    # Skip if tags
    if: startsWith(github.ref , 'refs/tags/') != true
    name: "Dependency Analysis"
    runs-on: ubuntu-latest
    needs: validation

    steps:
      - uses: actions/checkout@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Generates advice from Dependency-analysis Gradle task
        run: ./gradlew buildHealth

      - name: Upload advice
        uses: actions/upload-artifact@v2
        with:
          name: dependency-advice
          path: ./build/reports/dependency-analysis/
